In [59]:
print("Hallo Veendy, Selamat datang, semangat belajarnya ya Beb :)")

Hallo Veendy, Selamat datang, semangat belajarnya ya Beb :)


In [68]:
print('Hello, Ganteng !!!')

Hello, Ganteng !!!


### Contoh Pengkondisian If Else Sederhana

In [6]:
usia = 25
if usia >=17:
    print("Sudah memiliki KTP")
    print("Sudah dewasa")
else:
    print("Belum bisa memiliki KTP")
    print("Masih dibawah umur")

Sudah memiliki KTP
Sudah dewasa


## Membuat program sederhana Luas Persegi Panjang

In [12]:
#Masukkanlah data panjang dan lebar dari Bangun Persegi Panjang berikut:
panjang = float(input('Masukkan panjang = '))
lebar = float(input('Masukkan lebar = '))
#Hitung Luas
luas = (panjang*lebar)
#Cetak Luas
print('Luas persegi panjang = ', luas, 'm^2')

Masukkan panjang = 20
Masukkan lebar = 10
Luas persegi panjang =  200.0 m^2


# Pengkondisian pada Python

In [34]:
#Masukkan nilai
nama = str(input('Masukkan Nama = '))
nilai = float(input('Masukkan Nilai = '))
#kondisi, contoh cek kelulusan siswa
if(nilai >= 70):
    print(nama,'Selamat Anda lulus')
elif(nilai >= 64):
    print(nama,'Kamu harus mengikuti perbaikan')
else:
    print(nama,'Maaf Kamu tidak lulus')

Masukkan Nama = Budi
Masukkan Nilai = 63
Budi Maaf Kamu tidak lulus


## Pengulangan dengan while

In [49]:
#Contoh pengulangan dengan while (Contoh While ke-1)
ulang = 1
while(ulang <= 9):
    print('Perungan ke-',ulang)
    ulang+=1 #ini sama seperti ulang = ulang + 1
print("Perulangan Selesai")

Perungan ke- 1
Perungan ke- 2
Perungan ke- 3
Perungan ke- 4
Perungan ke- 5
Perungan ke- 6
Perungan ke- 7
Perungan ke- 8
Perungan ke- 9
Perulangan Selesai


In [53]:
#Contoh pengulangan dengan while + permintaan berapa jumlah perulangan yang diminta user (Contoh While ke-2)

#Meminta input jumlah perulangan dari pengguna
jumlah_perulangan = int(input("Masukkan jumlah perulangan: "))

ulang = 1
while(ulang <= jumlah_perulangan):
    print('Perulangan ke-', ulang)
    ulang += 1 # ini sama seperti ulang = ulang + 1

print("Perulangan Selesai")

Masukkan jumlah perulangan: 30
Perulangan ke- 1
Perulangan ke- 2
Perulangan ke- 3
Perulangan ke- 4
Perulangan ke- 5
Perulangan ke- 6
Perulangan ke- 7
Perulangan ke- 8
Perulangan ke- 9
Perulangan ke- 10
Perulangan ke- 11
Perulangan ke- 12
Perulangan ke- 13
Perulangan ke- 14
Perulangan ke- 15
Perulangan ke- 16
Perulangan ke- 17
Perulangan ke- 18
Perulangan ke- 19
Perulangan ke- 20
Perulangan ke- 21
Perulangan ke- 22
Perulangan ke- 23
Perulangan ke- 24
Perulangan ke- 25
Perulangan ke- 26
Perulangan ke- 27
Perulangan ke- 28
Perulangan ke- 29
Perulangan ke- 30
Perulangan Selesai


## Contoh Perulangan menggunakan For

In [54]:
#Contoh Perulangan For Sederhana
ulang = [1,3,5,7]
for x in ulang:
    print(x)

1
3
5
7


In [55]:
#Contoh Perulangan For lain.
hari = ['Senin', 'Rabu', 'Jumat']
for piket in hari:
    print("Saya tugas piket dihari", piket)

Saya tugas piket dihari Senin
Saya tugas piket dihari Rabu
Saya tugas piket dihari Jumat


#Rumus : for<target>in range(awal,akhir,range): pernyataan

In [56]:
#Implementasi rumus
#Contoh lain perulangan for menggunakan range
for x in range(5,15,2):
    print('perulangan ke-',x)

#Penjelasanya : Perulangan dimulai dari nilai awal 5 sampai nilai akhir 15 dengan step(kenaikan angka) sejumlah 2

perulangan ke- 5
perulangan ke- 7
perulangan ke- 9
perulangan ke- 11
perulangan ke- 13


#Perulangan Nested Loop (Nested Looping / Perulangan Bersarang)

#Rumus Nested Looping untuk menggunakan For:
for <target> in <obyek>:
    for<target> in <obyek>:
        pernyataan
    pernyataan

#Rumus Nested Looping untuk menggunakan While Loop:
while <ekspresi>:
    while <ekspresi>:
        pernyataan
    pernyataan

In [61]:
for i in range (2):
    for j in range(6,10,1):
        print("nilai i=",i," j=",j)
    print()
    
#Penjelasan : 

nilai i= 0  j= 6
nilai i= 0  j= 7
nilai i= 0  j= 8
nilai i= 0  j= 9

nilai i= 1  j= 6
nilai i= 1  j= 7
nilai i= 1  j= 8
nilai i= 1  j= 9



In [65]:
# Contoh Nested Looping dengan While Loop

i = 1  # Inisialisasi variabel untuk loop pertama
while i <= 3:  # Loop pertama berjalan selama i <= 3
    j = 1  # Inisialisasi variabel untuk loop kedua
    while j <= 3:  # Loop kedua berjalan selama j <= 3
        print(f"i: {i}, j: {j}")  # Output nilai i dan j
        j += 1  # Increment j untuk loop kedua
    i += 1  # Increment i untuk loop pertama


i: 1, j: 1
i: 1, j: 2
i: 1, j: 3
i: 2, j: 1
i: 2, j: 2
i: 2, j: 3
i: 3, j: 1
i: 3, j: 2
i: 3, j: 3


# Fungsi pada Python

#Mendefinisikan fungsi di Python

def namafungsi(argumen):
    pernyataan1
    pernyataan2
    return[ekspresi]

#argumen = input dari luar akan diproses di dalam fungsi
#return = opsional berguna untuk mengembaliakn nilai ekspresi dari sebuah fungsii jika diperlukan

In [85]:
#Membuat fungsi Sederhana pada Python
def halo():
    print("Hallo dunia, selamat bertemu, semoga harimu menyenangkan")
    print("Salam dari Jagakarsa, Jakarta Selatan, Perkenalkan saya Veendy")
    return

In [95]:
#Membuat Fungsi dengan argumen
def luaspersegipanjang(panjang,lebar):
    luas = panjang*lebar
    print("Luas Persegi Panjang = ", luas)

## Pemanggil Fungsi Sederhana

In [94]:
#Cara memanggil Fungsi sederhana  (CARA PANGGIL FUNGSI)
halo()

Hallo dunia, selamat bertemu, semoga harimu menyenangkan
Salam dari Jagakarsa, Jakarta Selatan, Perkenalkan saya Veendy


## Pemanggil Fungsi dengan Argumen 

In [93]:
#Cara memanggil Fungsi dengan Argumen pada luaspersegipanjang (CARA PANGGIL FUNGSI)
luaspersegipanjang(4,6)
#dimana 4 sebagai nilai variabel input panjang, dan 6 sebagai nilai variabel input lebar.

Luas Persegi Panjang =  24


In [1]:
#Memanggil Fungsi yang mengembalikan Nilai

def luaspersegipanjang1(panjang1,lebar1):
    luas1=panjang1*lebar1
    return luas1

#Pemanggilan fungsi
print ("Luas1: %d" % luaspersegipanjang1(6,3))

Luas1: 18


## Fungsi Rekursif = adalah fungsi yang memanggil dirinya sendiri, sehingga terjadilah perulangan di dalam fungsi tersebut.

#Contoh penggunaan Fungsi Rekursif

In [2]:
#Contoh penggunaan Fungsi Rekursif

#Fungsi Faktorial
def faktorial(n):
    if n<=1:
        return 1
    else:
        return n * faktorial(n-1)
    
#Program Utama
i = 0
n = int(input("Berapa Faktorial : "))

while i<=n:
    print(i,'! =', faktorial(i))
    i+=1 #ini artinya i=i+1


Berapa Faktorial : 2
0 ! = 1
1 ! = 1
2 ! = 2


# Variabel Lokal
#Variabel Lokal = variabel yang hanya bsa di akses di dalam  sebuah fungsi saja, dimana dia didefinisikan.

# Variabel Global
#Variabel Global dapat didefinikan variabel di luar fungsi sehingga memeiliki scope global (jangkauan global) bisa diakses dari mana saja. 

In [3]:
nama = "Veendy Suseno"
alamat = "Jakarta Selatan"

In [4]:
def testing():
    # ini variabel lokal
    nama = "Zulfina Alfalah"
    alamat = "Pekalongan Timur"
    # mengakses variabel lokal
    print("Nama: %s" % nama)
    print("Alamat: %s" % alamat)

In [5]:
# Mengakses variabel global
print("VARIABEL GLOBAL")
print("Nama: %s" % nama)
print("Alamat: %s" % alamat)

VARIABEL GLOBAL
Nama: Veendy Suseno
Alamat: Jakarta Selatan


In [6]:
# Memanggil fungsi (fungsi testing()):
print("VARIABEL LOKAL")
testing()

VARIABEL LOKAL
Nama: Zulfina Alfalah
Alamat: Pekalongan Timur


In [8]:
#Coba Digabungkan 

nama = "Veendy Suseno"
alamat = "Jakarta Selatan"

def testing():
    # ini variabel lokal
    nama = "Zulfina Alfalah"
    alamat = "Pekalongan Timur"
    # mengakses variabel lokal
    print("Nama: %s" % nama)
    print("Alamat: %s" % alamat)
    
# Mengakses variabel global
print("VARIABEL GLOBAL")
print("Nama: %s" % nama)
print("Alamat: %s" % alamat)

# Memanggil fungsi (fungsi testing()):
print("VARIABEL LOKAL")
testing()


VARIABEL GLOBAL
Nama: Veendy Suseno
Alamat: Jakarta Selatan
VARIABEL LOKAL
Nama: Zulfina Alfalah
Alamat: Pekalongan Timur


# Belajar Bab 7 Komputasi Matriks pada Python menggunakan Numpy

## A. Membuat Matriks

In [35]:
#Membuat Matriks dengan memanggil numpy
#import numpy library
import numpy as np

In [10]:
#Membuat Array
#Rumus = Nama_matriks = np.array([elemen_array])
A = np.array([3,5,7])
A

array([3, 5, 7])

In [11]:
#Untuk melihat dimensi dari array yang berupa (jumlah kolom dan baris)
#Menggunakan Rumus atau perintah = Nama_shape.shape
A.shape

(3,)

#Keterangan: Contoh diatas menunjukkan bahwa Matriks A merupakan matriks 1 dimensi dengan (3 kolom, 0 baris).

In [12]:
#Untuk melihat tipe data pada Matriks menggunakan perintah:
A.dtype

dtype('int32')

In [13]:
## Berikut adalah contoh membuat array 2 dimensi dengan tipe data pecahan (float).
B = np.array([[8.2,7.5,6],[4,3.5,3]])
B

array([[8.2, 7.5, 6. ],
       [4. , 3.5, 3. ]])

In [14]:
#Untuk melihat dimensi dari array yang berupa (jumlah kolom dan baris)
#Menggunakan Rumus atau perintah = Nama_shape.shape
B.shape

(2, 3)

In [16]:
#Untuk melihat tipe data pada Matriks menggunakan perintah:
B.dtype

dtype('float64')

In [17]:
## Contoh Matriks 2 x 3
C = np.array([[2,4],[5,8],[7,2]])
C

array([[2, 4],
       [5, 8],
       [7, 2]])

In [26]:
## Contoh Matriks 3 x 3
D = np.array([[1,2,3],[4,1,8],[3,7,2]])
D

array([[1, 2, 3],
       [4, 1, 8],
       [3, 7, 2]])

## B. Elemen Matriks

In [44]:
E = np.array([[2,4],[5,8],[7,2]])
print ("Matrik E:")
E

Matrik E:


array([[2, 4],
       [5, 8],
       [7, 2]])

In [52]:
E = np.array([[2,4],[5,8],[7,2]])
print("Elemen Matriks Baris 3 Kolom 2 pada Matrik E adalah = ")
E [2,1] #Jika ingin mengambil nilai matriks E elemen baris 3 kolom 2, maka dapat ditulis dengan E[2,1],
#mengingat array dimulai dari indeks 0.

Elemen Matriks Baris 3 Kolom 2 pada Matrik E adalah = 


2

In [53]:
E.shape #Dimensi array (kolom,baris)

(3, 2)

## C. Operasi Matriks

#Penjumlahan Matriks

In [58]:
F = np.array([[2,4],[5,8],[7,2]])
F

array([[2, 4],
       [5, 8],
       [7, 2]])

In [59]:
G = np.array([[1,3],[2,4],[5,2]])
G

array([[1, 3],
       [2, 4],
       [5, 2]])

In [61]:
#Penjumlahan Matriks F + Matriks G
F + G

array([[ 3,  7],
       [ 7, 12],
       [12,  4]])

In [64]:
#Lalu bila F + 10
F+10

array([[12, 14],
       [15, 18],
       [17, 12]])

#Pengurangan Matriks F- G

In [65]:
F-G

array([[1, 1],
       [3, 4],
       [2, 0]])

#Perkalian dan Pembagian pada Matriks

In [66]:
#Perkalian Matriks dengan angka tertentu
F * 10

array([[20, 40],
       [50, 80],
       [70, 20]])

In [67]:
#PErkalian 2 buah Matriks
F * G

array([[ 2, 12],
       [10, 32],
       [35,  4]])

In [69]:
#Perkalian Matriks dengan Skalar
F/2

array([[1. , 2. ],
       [2.5, 4. ],
       [3.5, 1. ]])

In [70]:
#Pembagian dengan 2 buah Matriks:
F/G

array([[2.        , 1.33333333],
       [2.5       , 2.        ],
       [1.4       , 1.        ]])

#Operasi SUM digunakan untuk menjumlahkan semua elemen.

In [71]:
F = np.array([[2,4],[5,8],[7,2]])
F

array([[2, 4],
       [5, 8],
       [7, 2]])

In [72]:
# Sum untuk semua elemen
np.sum(F)

28

In [73]:
#Sum untuk elemen axis
np.sum(F, axis=0)

array([14, 14])

In [78]:
#Sum untuk elemen axis
np.sum(F, axis=1)

array([ 6, 13,  9])

In [79]:
## Transpose matriks merupakan matriks yang dioperasikan dengan melakukan pertukaran elemen baris menjadi kolom dan elemen kolom menjadi baris dari matriks awalnya. Notasi dari matriks transpose biasanya dengan AT.

In [77]:
#Operasi Transppose
F.T

array([[2, 5, 7],
       [4, 8, 2]])

# C. Operasi Statistik Dasar 

In [80]:
#MEAN (Rata-rata)
nilai = np.array([7,6,8,9,5])
np.mean(nilai)

7.0

In [82]:
#MEDIAN (Nilai Tengah)
nilai = np.array([7,6,8,9,5])
np.median(nilai)

7.0

In [84]:
#Standar Deviasi
nilai = np.array([7,6,8,9,5,7,6,7,4,3])
np.std(nilai)

1.7204650534085253

In [85]:
#NILAI MAKSIMUM DAN MINIMUM PADA ARRAY
#NILAI MAKSIMUM
nilai = np.array([7,6,8,9,5,7,6,7,4,3])
np.max(nilai)

9

In [86]:
#NILAI MINIMUM
nilai = np.array([7,6,8,9,5,7,6,7,4,3])
np.min(nilai)

3